### ISSUE TITLE
No data points in Graphs

### ISSUE THREAD

**Issue by harikrish432** [a-schild/zabbix-ipsec#10]
I have done the configuration but i am not getting any data on graphs
![image](https://user-images.githubusercontent.com/32039646/51129824-812ae380-1851-11e9-96dc-cacb126cd176.png)

Kindly help me....

**Comment by a-schild** [comment]
Are the items active?
Perhaps they are not returning data because of some sudo issues or similar

**Comment by harikrish432** [comment]
Yes the items are active even the discovery rules items are active. Is it important to install fping to get any data to the graphs?

![image](https://user-images.githubusercontent.com/32039646/51162884-cd137200-18bd-11e9-935f-9c61fa342649.png)

**Comment by a-schild** [comment]
Yes, fping is required for this, just as mentioned in the readme file here:

https://github.com/a-schild/zabbix-ipsec/blob/master/README.md

**Comment by harikrish432** [comment]
Sorry for disturbing, Even after installing the Fping I am not able to get the graphs. Whereas discovery items are in enabled state and also reflecting the changes made in VPN backend server into the zabbix dashboards. Totally confused about the data points. Kindly help me.....
![image](https://user-images.githubusercontent.com/32039646/51185455-2d75d400-18fd-11e9-9e09-de82fa603263.png)
