### ISSUE TITLE
`<application_prototypes/>` required for version 3.0

### ISSUE THREAD

**Issue by jmvbxx** [a-schild/zabbix-ipsec#4]
I had to add `<application_prototypes/>` for the template to be imported into version 3.0.

I'd be happy to do a pull request for you.

**Comment by a-schild** [comment]
Please provide a pull request, I will integrate it

**Comment by ghost** [comment]
It was already integrated?

**Comment by a-schild** [comment]
No, no pull request was submitted

**Comment by ghost** [comment]
So, I assume that it does not work in Zabbix 3.2, isn't?

**Comment by a-schild** [comment]
Template is upgraded to zabbix 3.x but should also work with 3.0
