### ISSUE TITLE
Which target IP for a Nordvpn connection on Strongswan ?

### ISSUE THREAD

**Issue by squaria1** [a-schild/zabbix-ipsec#7]
Hi,
I'm sorry to disturb you but I can't find and do not understand where we find the target ip for a non local tunnel. I tried with server ip of nordvpn (like 192.230.46.143 [fr185.nordvpn.com]) but in the graph it says : "Trigger: Tunnel nordvpn endpoint 192.230.46.143 (*UNKNOWN*)" and "IPSec nordvpn endpoint rtt [no data]" , etc. So, could you explain it to me please.

**Comment by a-schild** [comment]
The target IP is just the other side of the VPN you wish to check for connectivity.
So if you have a LAN to LAN VPN, on side might be 192.168.1.1 and the other side is 192.168.18.1.

I haven't used nordvpn myself, so I don't know what connectivity it provides and how their network is structured
