### ISSUE TITLE
Item key not supported

### ISSUE THREAD

**Issue by harikrish432** [a-schild/zabbix-ipsec#9]
The Discovery rule is showing as Item not supported.
![image](https://user-images.githubusercontent.com/32039646/51110694-8b33ee80-181f-11e9-967d-2ac7ec1cf775.png)

Kindly help me.

**Comment by a-schild** [comment]
Have you created the ipsec.conf file in the zabbix config directory with the proper format?
It must be located in the location specified in your ipsec_checks.conf file

**Comment by harikrish432** [comment]
Thank you for your response, Yes its working now.
